### ISSUE TITLE
Add a param to allow version override

### ISSUE THREAD

**Issue by M3lkior** [asyncapi/html-template#107]
#### Reason/Context

In a CI/CD context, generated doc must be fit with the current project version. To achieve this today, we need to use external workaround to change the spec version on the fly.

It will be nice to have a new param `version` to allow scripting and dynamically change the generated version of HTML template

#### Description
Please try answering few of those questions
- What changes have to be introduced?

Add a new `version` param to allow executing ` ag asyncapi.yaml @asyncapi/html-template  -p version=1.0.0`
- Will this be a breaking change?

No

- How could it be implemented/designed?

Simply add a `version` param which override the `version` attribute in the specification

**Comment by derberg** [comment]
@M3lkior just to make sure, you do not want to provide a proper version in `info.version` but have a way to override it with `-p version=1.0.0`? Why do you consider a change in `info.version` as a workaround? AsyncAPI is a source of truth, better to change it there than override in the template, don't you think?

**Comment by M3lkior** [comment]
Yes it is the use case. AsyncAPI is my source of trust, except for the version which is  my project version (a java maven project)
I don't want to edit two files when upgrading version, for maintenability purposes so the simplest way is to dynamically change the asyncapi spec version with my `pom.xml` version (which is the source of truth in my release process) 

for now, i have a process that update the generated HTML file to package the doc with my project version

**Comment by derberg** [comment]
Sounds good. This will be optional so lgtm.

Only https://github.com/asyncapi/html-template/blob/master/template/index.html#L8 and https://github.com/asyncapi/html-template/blob/master/partials/sidebar.html#L18 need to be adjusted to read `params.version` first. Of course readme and [config](https://github.com/asyncapi/html-template/blob/master/package.json#L68) must be extended
