### ISSUE TITLE
JSON Map not rendering

### ISSUE THREAD

**Issue by InTheCloudDan** [asyncapi/html-template#12]
#### Describe the bug
Trying to get a map to render it throws an error. It could be my misunderstanding but I found a similar setup for an openapi spec that seems to be working.

```
Something went wrong:
TypeError: Cannot convert undefined or null to object
    at Function.entries (<anonymous>)
    at recursiveSchema (/Users/myuser/.nvm/versions/node/v12.13.1/lib/node_modules/@asyncapi/generator/node_modules/@asyncapi/parser/lib/models/asyncapi.js:272:49)
    at recursiveSchema (/Users/myuser/.nvm/versions/node/v12.13.1/lib/node_modules/@asyncapi/generator/node_modules/@asyncapi/parser/lib/models/asyncapi.js:273:11)
    at /Users/myuser/.nvm/versions/node/v12.13.1/lib/node_modules/@asyncapi/generator/node_modules/@asyncapi/parser/lib/models/asyncapi.js:327:11
    at Array.forEach (<anonymous>)
    at /Users/myuser/.nvm/versions/node/v12.13.1/lib/node_modules/@asyncapi/generator/node_modules/@asyncapi/parser/lib/models/asyncapi.js:325:40
    at Array.forEach (<anonymous>)
    at schemaDocument (/Users/myuser/.nvm/versions/node/v12.13.1/lib/node_modules/@asyncapi/generator/node_modules/@asyncapi/parser/lib/models/asyncapi.js:311:24)
    at assignIdToAnonymousSchemas (/Users/myuser/.nvm/versions/node/v12.13.1/lib/node_modules/@asyncapi/generator/node_modules/@asyncapi/parser/lib/models/asyncapi.js:346:3)
    at new AsyncAPIDocument (/Users/myuser/.nvm/versions/node/v12.13.1/lib/node_modules/@asyncapi/generator/node_modules/@asyncapi/parser/lib/models/asyncapi.js:25:5)
```

#### How to Reproduce
Steps to reproduce the issue. Attach all resources that can help us understand the issue:
``` myMessage:
      summary: A sent message.
      payload:
        type: object
        properties:
          myProperty:
            $ref: '#/components/schemas/myProperty'
          myProperty:
            type: object
            additionalProperties:
              $ref: '#/components/schemas/testObject'
        required: ["myProperty", "myMap"]
```

Edit: I've made some progress editing this line. https://github.com/asyncapi/html-template/blob/master/partials/schema-prop.html#L165 I'm not sure why it's `or prop.additionalProperties() === true` but now it just renders the property name placeholder:

![image](https://user-images.githubusercontent.com/10308834/80293611-9d911d80-872e-11ea-82a7-d736849f1c1f.png)

#### Expected behavior
That it would render out the docs. Not sure how it would look for a map.

**Comment by jamescrowley** [comment]
@InTheCloudDan I've been working in a similar area. additionalProperties() is permitted to be a boolean, or an object (hence the case for additionalProperties == true).

Your example has myProperty twice, and it would be helpful to see the definition of `testObject`. Can you post an example of the full schema?

**Comment by InTheCloudDan** [comment]
@jamescrowley thanks I see you're right! It ended up being user error on my part! Is there any examples of having the tempate render out something other than `(property name)`? I haven't been successful in that.

**Comment by jamescrowley** [comment]
@InTheCloudDan you won't be able to, as far as I know, as there's no way to specify property names in additionalProperties.

from https://json-schema.org/understanding-json-schema/reference/object.html :

> If additionalProperties is an object, that object is a schema that will be used to validate any additional properties not listed in properties.

So using additionalProperties, you specify the type they have to comply with, but not the names themselves.

**Comment by InTheCloudDan** [comment]
Thanks for pointing that out! I was just hoping to generate a bit more pointed example than `property1` `property2` for users to see, but this has been great to work with!
