### ISSUE TITLE
Minify and purge CSS files

### ISSUE THREAD

**Issue by Theiaz** [asyncapi/html-template#126]
Hello all! Today I've found this nice project and want to give some ideas.

#### Reason/Context

Having a look at `tailwind.min.css` it seems like there has been no pruning. File size is nealry 400KB and I think there are much unused styles. Without pruning one big advantge of TailwindCSS is missed ([similar case](
https://v1.tailwindcss.com/docs/installation#using-tailwind-via-cdn)). I think the file size would be reduced significantly. For further information have a look at [TailwindCSS documentation](https://v1.tailwindcss.com/docs/controlling-file-size).

Additionally `main.css` could also be minified to reduce file size.

**Comment by derberg** [comment]
@Theiaz hey, you mean you'd like to have a kind of post-processing of the resulting generation output? or is there something that needs to be improved in the HTML files to enable any custom post-processing anyone can add?

**Comment by Theiaz** [comment]
@derberg Hello

I think its necessary to introduce post-processing with the generated ouput. HTML files/partials looks fine to me. 

There is no need to include a separate `tailwind.min.css`. Instead you can setup the tailwind dependency via npm, add a `tailwind.config.js` and adjust `main.css` (if I'm right). Have a look at [Installation Guide](https://v1.tailwindcss.com/docs/installation).  Maybe I can try to help with a pull request if I got time.

Take care I've linked the old version (v1) of TailwindCSS to prevent breaking changes.

**Comment by derberg** [comment]
PR would be welcome. Triggering of post-processing could be done in an automated way as we do with PDF generation -> https://github.com/asyncapi/html-template/blob/master/hooks/generatePdf.js

**Comment by Theiaz** [comment]
Seems like your `tailwind.min.css` is using very old styles and is not more compatible with newest TailwindCSS versions. For example there is no more class `.bg-blue-dark`. I do not know where the current styles are from, however it seems pretty similar to [this](https://github.com/tailwindlabs/tailwindcss-plugin-examples/blob/master/dist/styles.css).

I will investigate what to do if the newest Tailwind versions needs to be used. For sure, the CSS classes of the partials needs to be adjusted.
