### ISSUE TITLE
Css files not minified

### ISSUE THREAD

**Issue by Theiaz** [asyncapi/html-template#160]
#### Describe the bug
Css files are not minified. 

[main.min.css](https://github.com/asyncapi/html-template/blob/master/template/css/main.min.css)
#### Expected behavior
Css files should be minified.

Possible solution could be to use [cssnano](https://github.com/cssnano/cssnano) with postcss plugin. Needs to wait for #159.

**Comment by derberg** [comment]
@magicmatatjahu how does the default css file set up in the react component, the one that holds styles like the main.min.css? Do you minify it or this is something planned for later?

**Comment by magicmatatjahu** [comment]
@derberg "New" React component will have a `default.css` and `default.min.css` styles, and we will use in html-template minified version :)

**Comment by magicmatatjahu** [comment]
Supported in `@asyncapi/html-template@0.21.0` :)
