### ISSUE TITLE
Title contains <span> tags around version

### ISSUE THREAD

**Issue by edubsi** [asyncapi/html-template#167]
#### Describe the bug
Starting with version 0.18.0 <span> </span> tags are wrapping the version information.

#### How to Reproduce
Should always happen when a title is displayed. The Title of the tab will display `MyAPI <span>1.0.0</span>` e.g.

#### Expected behavior
The version information in the Title should not be wrapped with `<span>` tags.

**Comment by magicmatatjahu** [comment]
@edubsi Hi! Sorry for late response. Currently we are unifying HTML-Template with React component in this PR https://github.com/asyncapi/html-template/pull/166 I fixed this bug in unification. Could you wait for it (max next 2 weeks)?

**Comment by edubsi** [comment]
Hi! Yes 2 weeks should be no problem.
Thanks for the fix 👍

**Comment by magicmatatjahu** [comment]
Fixed in `@asyncapi/html-template@0.21.0` @edubsi  Reopen if will you found bugs, and sorry for delay 😅
