### ISSUE TITLE
Move to JSX renderer

### ISSUE THREAD

**Issue by magicmatatjahu** [asyncapi/html-template#185]
#### Reason/Context

Currently template is written in Nunjuck. We should move to JSX (aka React) renderer, of course after [unification](https://github.com/asyncapi/html-template/issues/51). Unfornatelly we are blocked by https://github.com/asyncapi/generator/issues/521. After improving compilation of React templates, switching to React template will be very easy.

**Comment by magicmatatjahu** [comment]
Still walid. I will annotate that by `good first issue` label.

**Comment by ritik307** [comment]
@derberg @magicmatatjahu I would like to work on it but can you kindly elaborate on the issue

**Comment by magicmatatjahu** [comment]
@ritik307 Hello! Yeah, no problem, we can discuss. Main improvement here will be change Nunjucks templates to the JSX files (React components). Atm our generator supports two render engines, mentioned Nunjucks and JSX - more info about JSX and Nunjucks is here:
- JSX https://github.com/asyncapi/generator/blob/master/docs/authoring.md#react-1
- Nunjucks https://github.com/asyncapi/generator/blob/master/docs/authoring.md#nunjucks

We have also https://github.com/asyncapi/template-for-generator-templates repo when you can check that same templates written in Nunjucks and JSX to check difference how to achieve that same output:
- Nunjucks https://github.com/asyncapi/template-for-generator-templates/blob/nunjucks/template/index.html
- JSX https://github.com/asyncapi/template-for-generator-templates/blob/master/template/index.js 

We are opened for contributions :)

So some actions points to that issue:
- you should change that file https://github.com/asyncapi/html-template/blob/master/template/index.html to the JSX template
- we should still support all parameters that we have for that template https://github.com/asyncapi/html-template#supported-parameters
- all hooks should also work after rewriting template

It sounds as big change, but you can make it by iteration, please rewriting in first step the mentioned file to JSX and we can discuss about next changes :)

**Comment by ritik307** [comment]
hi @magicmatatjahu correct me if am wrong, initially, I have to convert `index.html` to a JSX template `index.jsx`

**Comment by magicmatatjahu** [comment]
@ritik307 Yes exactly, but you can use `.js` extension, not `.jsx` :)

**Comment by ritik307** [comment]
@magicmatatjahu I am currently facing so many errors while setting up the project. Can you kindly provide me with the steps to set up the project correctly? 

Following are the steps that I followed while setting up the project.

1. npm install -g @asyncapi/generator.
2. npm run develops (showed errors that files are missing so I ran npm install but it is still showing some error).
3. npm run develop:install (still showing errors)
![ss1](https://user-images.githubusercontent.com/22374829/150387248-c6325910-ddff-46ee-9d16-446a017f4d8e.png)
![ss1](https://user-images.githubusercontent.com/22374829/150387525-6a43a1f1-d51c-4664-a0c4-83746909b17d.png)

**Comment by magicmatatjahu** [comment]
@ritik307 Strange, I will check that, but you can also use that steps to test your changes:

```
# install deps in project
npm install

# run generator
ag https://raw.githubusercontent.com/asyncapi/generator/v1.1.5/test/docs/dummy.yml ./ -o ./output --force-write --watch-template
```

**Comment by ritik307** [comment]
> @ritik307 Strange, I will check that, but you can also use these steps to test your changes:
> 
> ```
> # install deps in project
> npm install
> 
> # run generator
> ag https://raw.githubusercontent.com/asyncapi/generator/v1.1.5/test/docs/dummy.yml ./ -o ./output --force-write --watch-template
> ```

It worked 🎉 but I am getting a small error
![ss1](https://user-images.githubusercontent.com/22374829/150390242-d2119d97-7656-4af6-8ff4-c76e19d46423.png)

**Comment by magicmatatjahu** [comment]
Personally I don't use `--watch-template` flag. I always generate template by:

```
ag https://raw.githubusercontent.com/asyncapi/generator/v1.1.5/test/docs/dummy.yml ./ -o ./output --force-write
```

after some changes to not to make unnecessary generations. If you will have any problems/question please ask :)

**Comment by ritik307** [comment]
got it
