### ISSUE TITLE
Construct message example from schema composition

### ISSUE THREAD

**Issue by DavidBiesack** [asyncapi/html-template#188]
#### Reason/Context

At present, when defining examples in the components/schemas section, it is very tedious to author complete
examples. Use tooling (such as from `openapi-sampler` which is used in [widdershins](https://github.com/Mermade/widdershins) for OpenAPI) which will construct more complete examples by merging the examples from `allOf` constructs 

#### Description

See a sample `asyncapi.yaml` file in comment below
All the messages extend from a common `abstractMessage` schema.
All the messages in the `example` channel extend from a `abstractExampleSchema` which uses `abstractMessage`
and also defines additional properties `a` and `b`.
At present, I have to explicitly copy the `id`, `version`, `a`, `b` and other "inherited" properties in each message
example; this is both tedious and error prone. It would be nice if I only had to specify properties in each schema
that are defined in that schema or which need to override values (such as `version` in `messageX`).

**Comment by magicmatatjahu** [comment]
@DavidBiesack Hello! Thanks for issue. Could you attach content of file as plain content in comment as code block? It may be weird, but we try not to open any files uploaded to github in issues.

**Comment by DavidBiesack** [comment]
Here is the `asyncapi.yaml` source:
```
asyncapi: 2.0.0
id: https://www.example.com/example
info:
  title: example with message schema composition
  description: >-
    example with message schema composition
  contact:
    name: Apiture
    email: api@apiture.com
    url: https://developer.apiture.com
  version: 0.1.0

servers:
  example:
    url: https://www.example.com/queue
    description: a message queue
    protocol: amqp

tags:
  - name: Example
    description: Example
  - name: Accounts

channels:
  example:
    description: Example chanel
    publish:
      operationId: example
      summary: Example
      description: Fired after ...
      message:
        oneOf:
          - name: messageA
            payload:
              $ref: '#/components/schemas/messageA'
              title: Message C
              tags:
                - name: Example
          - name: messageB
            payload:
              $ref: '#/components/schemas/messageB'
              title: Message B
              tags:
                - name: Example
          - name: messageX
            payload:
              $ref: '#/components/schemas/messageX'
              title: Message X
              tags:
                - name: Example

components:
  schemas:

    abstractMessage:
      title: Abstract Message
      description: Base abstract schema for all event message schemas.
      x-apiture-fragment: true
      properties:
        id:
          description: >-
            The unique ID of this event. This is an opaque string.
          type: string
          maxLength: 48
        occurredAt:
          description: >-
            The [RFC 3339](https://tools.ietf.org/html/rfc3339) date-time (UTC)
            when the event occurred.
          type: string
          format: date-time
        version:
          description: >-
            The [semantic version](https://semver.org/spec/v2.0.0.html) number of this message's schema.
          type: string
          format: semantic-version
          example: 1.0.0
      required:
        - id
        - occurredAt
        - version
      example:
        id: 7de58ab9-3ffd-40fb-a50c-b5e12e239179
        occurredAt: '2021-05-03T08:45:42.375Z'
        version: 1.0.0
    exampleProperties:
      title: Example Properties
      description: Some reusable Properties ....
      type: object
      allOf:
        - type: object
          properties:
            a:
              description: Something
              type: string
              maxLength: 48
            b:
              description: Another thing
              type: string
              minLength: 8
              maxLength: 32
          required:
            - a
            - b
      example:
        a: aAAa
        b: BB
    abstractExampleMessage:
      title: Abstract Example Message
      description: An abstract schema for all messages in the example channel
      type: object
      allOf:
        - $ref: '#/components/schemas/abstractMessage'
        - $ref: '#/components/schemas/exampleProperties'
        - type: object
          required:
            - example
          properties:
            example:
              description: true if ....
              type: boolean
      example:
        id: 7de58ab9-3ffd-40fb-a50c-b5e12e239179
        occurredAt: '2021-05-03T08:45:42.375Z'
        version: 1.2.0
        a: aAAa
        b: BB
        example: true
    messageA:
      Title: Message A
      description: Message A
      allOf:
        - $ref: '#/components/schemas/abstractExampleMessage'
      example:
        id: 7de58ab9-3ffd-40fb-a50c-b5e12e239179
        occurredAt: '2021-05-03T08:45:42.375Z'
        version: 2.1.0
        a: aAAcc
        b: BBcc
    messageB:
      Title: Message B
      description: Message B
      allOf:
        - $ref: '#/components/schemas/abstractExampleMessage'
      example:
        id: 7de58ab9-3ffd-40fb-a50c-b5e12e239179
        occurredAt: '2021-05-03T08:45:42.375Z'
        version: 1.3.0
        a: aAAbb
        b: BBbb
    messageX:
      Title: Message X
      description: Message X
      allOf:
        - $ref: '#/components/schemas/abstractExampleMessage'
        - type: object
          properties:
            x:
              type: string
          required:
            - x
          example:
            x: foo
      example:
        version: 1.0.0
        x: bar
```

**Comment by magicmatatjahu** [comment]
I checked example with our playground and we also use `openapi-sampler` under the hood. You can see it [here](https://github.com/asyncapi/generator-filters/blob/master/src/customFilters.js#L76). Widdershins also uses (as you mentioned) `openapi-sampler` [here](https://github.com/Mermade/widdershins/blob/master/lib/common.js#L442). I don't see in code that Widdershins merges `allOf` before generating example. I only know that `openapi-sampler` do it before generating.

**Comment by derberg** [comment]
tagging @MikeRalphson for Widdershins.

As a side note, there is a library we could use here https://github.com/mokkabonna/json-schema-merge-allof but as an option in my opinion, have a toogle that you can click and get merged allOf. But in general I think the way to go is merge schema and therefore get merged generated example, and not that we keep schema as allOf and only example is merged

have a look at https://github.com/asyncapi/html-template/issues/11

**Comment by MikeRalphson** [comment]
Do you always want to merge `allOf`s? `allOf` (as you know) says the instance must be valid against all of these subschemas independently, not that "the author split a schema into subschemas for no reason and they can be trivially merged".

**Comment by derberg** [comment]
> the author split a schema into subschemas for no reason and they can be trivially merged

I was actually always thinking "the author split a schema into subschemas on purpose to just troll me" 😆 

I definitely agree that this should not be a default, but an option that one can select in the UI

**Comment by DavidBiesack** [comment]
I'll try to get to this in the next couple weeks

**Comment by DavidBiesack** [comment]
I'm not referring to merging the `allOf` schema presentation in the middle panel (although that would be a useful feature), but rather the  example shown in the rightmost panel when I select an operation on the left navigation. At present,
html-template shows only the properties in the top-level example of the message schema, not those from other `allOf` schemas used to compose the message schema.

Here is a better example:

```yaml
asyncapi: 2.0.0
id: https://www.example.com/example
info:
  title: example with message schema composition
  description: >-
    example with message schema composition
  contact:
    name: Apiture
    email: api@apiture.com
    url: https://developer.apiture.com
  version: 0.1.0

servers:
  example:
    url: https://www.example.com/queue
    description: a message queue
    protocol: amqp

tags:
  - name: Example
    description: Example
  - name: Accounts

channels:
  example:
    description: Example chanel
    publish:
      operationId: example
      summary: Example
      description: Fired after ...
      message:
        name: messageX
        payload:
          $ref: '#/components/schemas/messageX'
          title: Message X
          tags:
            - name: Example

components:
  schemas:

    abstractMessage:
      title: Abstract Message
      description: Base abstract schema for all event message schemas.
      x-apiture-fragment: true
      properties:
        id:
          description: >-
            The unique ID of this event. This is an opaque string.
          type: string
          maxLength: 48
        occurredAt:
          description: >-
            The [RFC 3339](https://tools.ietf.org/html/rfc3339) date-time (UTC)
            when the event occurred.
          type: string
          format: date-time
        version:
          description: >-
            The [semantic version](https://semver.org/spec/v2.0.0.html) number of this message's schema.
          type: string
          format: semantic-version
          example: 1.0.0
      required:
        - id
        - occurredAt
        - version
      example:
        id: 7de58ab9-3ffd-40fb-a50c-b5e12e239179
        occurredAt: '2021-05-03T08:45:42.375Z'
        version: 1.0.0
    exampleProperties:
      title: Example Properties
      description: Some reusable Properties ....
      type: object
      properties:
        s1:
          description: Something
          type: string
          maxLength: 48
        s2:
          description: Another thing
          type: string
          minLength: 8
          maxLength: 32
      required:
        - s1
        - s2
      example:
        s1: aAAa
        s2: BB
    abstractExampleMessage:
      title: Abstract Example Message
      description: An abstract schema for all messages in the example channel
      type: object
      allOf:
        - $ref: '#/components/schemas/abstractMessage'
        - $ref: '#/components/schemas/exampleProperties'
    messageA:
      Title: Message A
      description: Message A
      allOf:
        - $ref: '#/components/schemas/abstractExampleMessage'
        - type: object
          properties:
            a:
              description: A
              type: string
              maxLength: 48
      example:
        a: aAAcc
    messageB:
      Title: Message B
      description: Message B
      allOf:
        - $ref: '#/components/schemas/messageA'
        - type: object
          properties:
            b:
              description: B
              type: string
              maxLength: 48
      example:
        b: Bbbbb
    messageX:
      Title: Message X
      description: Message X
      allOf:
        - $ref: '#/components/schemas/messageB'
        - type: object
          properties:
            x:
              type: string
          required:
            - x
          example:
            x: foo
      example:
        x: bar
```

When I click on the sole `Example` operation in the HTML, the right column shows only

```json
{
  "x": "bar"
}
```

However, the (effective) composed schema has other examples; I'd like them merged to show:

```json
{
  "id": "7de58ab9-3ffd-40fb-a50c-b5e12e239179",
  "occurredAt": "2021-05-03T08:45:42.375Z",
  "version": "1.0.0",
  "s1": "aAAa",
  "s2": "BB",
  "a": "aAAcc",
  "b": "Bbbbb",
  "x": "bar"
}
```

so I would like (expect) the properties from the examples in `abstractMessage`, `abstractExampleMessage`, `messageA`, and `messageB` to be rendered in the example (especially since `id`, `occurredAt`, and `version` are `required` but that is secondary).

**Comment by magicmatatjahu** [comment]
@DavidBiesack Thanks for good explanation of your problem on complex example. I'm very appreciate that. 

```json
{
  "x": "bar"
}
```

output is intended. I hasten to explain on the `messageX` schema from your spec:

```yaml
    messageX:
      Title: Message X
      description: Message X
      allOf:
        - $ref: '#/components/schemas/messageB'
        - type: object
          properties:
            x:
              type: string
          required:
            - x
          example:
            x: foo
      example:
        x: bar
```

you have defined `allOf` but in the root of the schema you have defined manually `example` as `x: bar`. Under the hood we use the [openapi-sampler](https://github.com/Redocly/openapi-sampler) and it works in this way that first checks `const`, `examples`, `enum` and `default` keywords where possible (in this order) and if doesn't find any, then creates the example programmatically based on schema, so in your example lib checks on `messageX` the `example` keyword and ends the processing.

To achieve the:

```json
{
  "id": "7de58ab9-3ffd-40fb-a50c-b5e12e239179",
  "occurredAt": "2021-05-03T08:45:42.375Z",
  "version": "1.0.0",
  "s1": "aAAa",
  "s2": "BB",
  "a": "aAAcc",
  "b": "Bbbbb",
  "x": "bar"
}
```

example you should remove from the root `example` keyword in `messageX`, `messageB`, `messageA` - in schemas where you have defined `allOf` keyword. I removed it and I have this:

![image](https://user-images.githubusercontent.com/20404945/127707764-53b9a517-cc2b-4350-8a9d-d3b5ed4beaad.png)

> `a` and `b` are generated programmatically by `openapi-sampler` but rest of properties are inferred from `example` field.

[openapi-sampler](https://github.com/Redocly/openapi-sampler) is simple library which is super fast, very lightweight and that's why we use it to reduce the weight of the html-template (and also of react-component which works under the hood).

I hope that it's clear. Do you have any other questions/concerns?

**Comment by DavidBiesack** [comment]
Thanks --- I was hoping the `openapi-sampler` would help me more. What I really want to do is to express only _changed_ properties in each example. I guess I can't do it with a top-level `example` in each schema, although I think I can do it with examples in the schemas within the `allOf` or `properties`. It's a bit more indirect, but I think I can make it work.
