### ISSUE TITLE
Rendering markdown tables broken since 0.21.0

### ISSUE THREAD

**Issue by mitchellrj** [asyncapi/html-template#194]
#### Describe the bug
Markdown tables in free text (e.g. a field description) worked before 0.21.0, but now they render as plain text.

#### How to Reproduce

Put a markdown table in your schema and render it.

#### Expected behavior

Previous appearance:
![image](https://user-images.githubusercontent.com/147070/117668061-17a70f80-b195-11eb-9061-1ea3c9f10a95.png)

New appearance: 
![image](https://user-images.githubusercontent.com/147070/117668239-47561780-b195-11eb-8678-6ec1998cc26e.png)

**Comment by magicmatatjahu** [comment]
@mitchellrj Hello! Thanks for reporting the bug. As I see you have a wrong markdown. We switched in `0.21.0` to the new markdown renderer (which is more strict) with new styling. For example, if I rewrote your example to:

```md
| command | heading 2 | description |
| --- | --- | --- |
| example | Yes | Reticulates the splines |
``` 

Then I have 
![image](https://user-images.githubusercontent.com/20404945/117673419-1385ec80-b1ab-11eb-9c16-fcef28ac87d9.png)

Please fix markdown and let us know about next problems :)

**Comment by mitchellrj** [comment]
Ah yes, the only mistake was not including a blank line above the existing table. Thanks!
