### ISSUE TITLE
Unable to generate : prevRenderer issue

### ISSUE THREAD

**Issue by sl-nigelalmada** [asyncapi/html-template#214]
#### Describe the bug
Since today (16/06/2021) I'm unable to the HTML bundled file based on our AsyncApi doc
[Maybe the issue is related to yesterday release ? ](https://github.com/asyncapi/html-template/releases/tag/v0.22.0)

The error : 

```
Something went wrong:
[...]/node_modules/@asyncapi/generator/node_modules/marked/src/marked.js:158
          const prevRenderer = extensions.renderers?.[ext.name];
                                                    ^

SyntaxError: Unexpected token '.'
    at wrapSafe (internal/modules/cjs/loader.js:915:16)
    at Module._compile (internal/modules/cjs/loader.js:963:27)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
    at Module.load (internal/modules/cjs/loader.js:863:32)
    at Function.Module._load (internal/modules/cjs/loader.js:708:14)
    at Module.require (internal/modules/cjs/loader.js:887:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> ([...]/node_modules/@asyncapi/generator/node_modules/@asyncapi/react-component/src/helpers/marked.ts:1:1)
    at Module._compile (internal/modules/cjs/loader.js:999:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
```

#### How to Reproduce

Use the command : `npx ag spec.yaml @asyncapi/html-template --force-write -p singleFile=true -p outFilename=index.html`

The `package.json` file sets the `asyncapi/generator` dependency at `^1.7.0`

Content of the `spec.yaml` file : 

```yaml
asyncapi: 2.0.0
info:
  title: Account Service
  version: 1.0.0
  description: This service is in charge of processing user signups
channels:
  user/signedup:
    subscribe:
      message:
        $ref: '#/components/messages/UserSignedUp'
components:
  messages:
    UserSignedUp:
      payload:
        type: object
        properties:
          displayName:
            type: string
            description: Name of the user
          email:
            type: string
            format: email
            description: Email of the user
```

I tried to downgrade `asyncapi/generator` and/or `asyncapi/html-template` versions (by using a specific version in the npx command for `asyncapi/html-template`) but all my tries generates the same error

#### Expected behavior

Being able to generate the HTML file like before today

TIA

**Comment by magicmatatjahu** [comment]
@sl-nigelalmada Hi! It's probably due to fact that one PR in the repo https://github.com/asyncapi/asyncapi-react in the `next` branch (we use underline the react-component to render the template) had updated the `marked` dependency where someone used the optional chaining in JS -> doc for that https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Optional_chaining

I will check that and I will give you the answer as soon as possible.

In meantime, could you write your NodeJS version? I know that writing `for me it works` is stupid, but I have `14.16.1` version and everything works :)

![image](https://user-images.githubusercontent.com/20404945/122216467-ba496100-ceac-11eb-8360-950beccab5fe.png)

We changed the way of rendering the JSON examples (only styling) and I have it, so I use the newest version of template

![image](https://user-images.githubusercontent.com/20404945/122216579-d77e2f80-ceac-11eb-8e82-e455ac403477.png)

**Comment by magicmatatjahu** [comment]
@sl-nigelalmada As I thought, from tis [PR](https://github.com/markedjs/marked/pull/2043) (merged the 13 hours ago) people in markedJS started using the optional chaining, so please update your NodeJS at least to 14 version :) You can use the https://www.npmjs.com/package/n package to have several versions if you need. Please write if you need something more! :)

**Comment by sl-nigelalmada** [comment]
@magicmatatjahu I'm using NodeJS v12.22.1
I will evaluate the impacts of upgrading to 14+ I will get back to you

**Comment by magicmatatjahu** [comment]
@sl-nigelalmada Good to hear :)

@jonaslagoni I don't think so :P we should use always the latest 2.X.X version of marked, probably the maintainers will change the optional chaining to normal `? :` statement.

**Comment by jonaslagoni** [comment]
Yea, but we cannot wait until they get that solved, who knows when? For now, we should probably downgrade the dependency so the users are not affected on our end.

**Comment by derberg** [comment]
yup, I agree with @jonaslagoni 
they broke semver, but no clear answer in their issue when they will provide a fix, even though they are advanced https://github.com/markedjs/marked/pull/2109

**Comment by magicmatatjahu** [comment]
I created the PR https://github.com/asyncapi/asyncapi-react/pull/371. After merging markedjs/marked#2109 I will revert changes :)

**Comment by jonaslagoni** [comment]
@magicmatatjahu guess you can revert it now 😆

**Comment by magicmatatjahu** [comment]
f*****g package 😂 I will revert it in the next PRs 😄

**Comment by magicmatatjahu** [comment]
If someone will have similar problems, please reopen the issue :)
