### ISSUE TITLE
'TypeError: schema.isBooleanSchema is not a function' when using Docker Image

### ISSUE THREAD

**Issue by uucly** [asyncapi/html-template#220]
Hi,

i am using the current docker image asyncapi/generator with this command

`docker run --rm \
-v ${PWD}/src/main/resources/asyncapi.yml:/app/asyncapi.yml \
-v ${PWD}/src/main/resources/static:/app/output \
asyncapi/generator -o /app/output /app/asyncapi.yml @asyncapi/html-template --force-write`

So if i start to generate i get the following error

Something went wrong:
Template render error: (/usr/local/lib/node_modules/@asyncapi/generator/node_modules/@asyncapi/html-template/template/index.html) [Line 7, Column 57]
  TypeError: schema.isBooleanSchema is not a function
    at Object._prettifyError (/usr/local/lib/node_modules/@asyncapi/generator/node_modules/nunjucks/src/lib.js:36:11)
    at /usr/local/lib/node_modules/@asyncapi/generator/node_modules/nunjucks/src/environment.js:563:19
    at Template.root [as rootRenderFunc] (eval at _compile (/usr/local/lib/node_modules/@asyncapi/generator/node_modules/nunjucks/src/environment.js:633:18), <anonymous>:56:3)
    at Template.render (/usr/local/lib/node_modules/@asyncapi/generator/node_modules/nunjucks/src/environment.js:552:10)
    at Environment.renderString (/usr/local/lib/node_modules/@asyncapi/generator/node_modules/nunjucks/src/environment.js:380:17)
    at /usr/local/lib/node_modules/@asyncapi/generator/lib/renderer/nunjucks.js:32:14
    at new Promise (<anonymous>)
    at nunjucksExport.renderNunjucks (/usr/local/lib/node_modules/@asyncapi/generator/lib/renderer/nunjucks.js:31:10)
    at Generator.renderFile (/usr/local/lib/node_modules/@asyncapi/generator/lib/generator.js:701:12)
    at Generator.renderAndWriteToFile (/usr/local/lib/node_modules/@asyncapi/generator/lib/generator.js:615:27)

![Bildschirmfoto 2021-06-22 um 15 37 19](https://user-images.githubusercontent.com/5304588/122934403-ca12ea80-d36f-11eb-803b-01398d367288.png)

22 hours ago everything worked fine.
It seems like the node.js version changed.

Could you please have a look.

Best regards,
Sven Weisker

**Comment by jonaslagoni** [comment]
@magicmatatjahu I see it is related to the boolean schema feature you implemented on the parser. Anything that has not been changed correctly here?

**Comment by jonaslagoni** [comment]
Related PR - https://github.com/asyncapi/generator/pull/601

The generator does not use the newest version yet 🤦

**Comment by magicmatatjahu** [comment]
Hmmm... 🤔 Strange. When I try to generate html-template from the newest version on npm I will get this same error, but when I generate locally from source from from latest revision, everything works:

![image](https://user-images.githubusercontent.com/20404945/122937203-12cba300-d372-11eb-931d-301452b58efd.png)

> The generator does not use the newest version yet 🤦 Guess it was a generator bug after all 😅

But in component we uses the newest version of parser and it's probably thrown from https://github.com/asyncapi/asyncapi-react/blob/next/library/src/helpers/schema.ts#L67 line. I also wrote test for cases when schema isn't the Schema instance... So probably the component uses the 1.5.2, but html-template 1.5.1.

**Comment by jonaslagoni** [comment]
The problem is that the template receives a schema object based on the version the generator uses. And the generator had a failed release pipeline, so it was never updated, meaning the schema object provided was from parser version `1.5.1`

**Comment by magicmatatjahu** [comment]
> The problem is that the template receives a schema object based on the version the generator uses. And the generator had a failed release pipeline, so it was never updated, meaning the schema object provided was from parser version 1.5.1

Ahh... Yes... 🤦🏼 And this parsed schema hasn't new functions.

**Comment by jonaslagoni** [comment]
@uucly feel free to reopen the issue if you have further issues 🙂

**Comment by uucly** [comment]
Hey guys. Thanks for your quick support.

**Comment by magicmatatjahu** [comment]
@uucly ❤️ 

Please remember to use the newest version of docker image with `1.7.3` version of `@asyncapi/generator` :)
