### ISSUE TITLE
html-template: apparent problem with generate:before hook

### ISSUE THREAD

**Issue by btimby** [asyncapi/html-template#252]
#### Describe the bug

I am using the following packages:

```javascript
...
    "@asyncapi/generator": "^1.8.2",
    "@asyncapi/html-template": "^0.23.7",
    "@asyncapi/parser": "^1.7.0",
...
```

I am receiving the following error:

```javascript
(node:1935853) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'info' of undefined
    at generate:before (/home/btimby/Code/node_modules/@asyncapi/html-template/hooks/00_changeSpecVersion.js:6:56)
    at /home/btimby/Code/node_modules/@asyncapi/generator/lib/generator.js:792:20
    at Array.map (<anonymous>)
    at Generator.launchHook (/home/btimby/Code/node_modules/@asyncapi/generator/lib/generator.js:789:28)
    at Generator.generate (/home/btimby/Code/node_modules/@asyncapi/generator/lib/generator.js:190:16)
```

I found that disabling the hook would avoid the error. Further, the change in this PR also seems to fix the issue. The problem is that the first argument to the hook is an instance of `Generator`, which does not have an `asyncapi` attribute, thus the `asyncapi` variable is undefined.

#### How to Reproduce

I am using this simple test script:

```javascript
const Generator = require('@asyncapi/generator');
const Parser = require('@asyncapi/parser');
const asyncApiDocument = require('./spec/ws.json');

const generator = new Generator(
  '@asyncapi/html-template',
  null,
  {
    entrypoint: 'index.html',
    output: 'string',
    // There seems to be a bug in this hook.
/*    disabledHooks: {
      'generate:before': [
        'generate:before',
      ],
    },*/
    templateParams: {
      singleFile: true,
    }
  }
);

Parser.parse(asyncApiDocument).then((doc) => {
  generator.generate(doc).then((html) => console.log(html));
});
```

I am using the example schema:

```json
{
  "asyncapi": "2.1.0",
  "info": {
    "title": "Streetlights API",
    "version": "1.0.0",
    "description": "The Smartylighting Streetlights API allows you\nto remotely manage the city lights.\n",
    "license": {
      "name": "Apache 2.0",
      "url": "https://www.apache.org/licenses/LICENSE-2.0"
    }
  },
  "servers": {
    "mosquitto": {
      "url": "mqtt://test.mosquitto.org",
      "protocol": "mqtt"
    }
  },
  "channels": {
    "light/measured": {
      "publish": {
        "summary": "Inform about environmental lighting conditions for a particular streetlight.",
        "operationId": "onLightMeasured",
        "message": {
          "name": "LightMeasured",
          "payload": {
            "type": "object",
            "properties": {
              "id": {
                "type": "integer",
                "minimum": 0,
                "description": "Id of the streetlight."
              },
              "lumens": {
                "type": "integer",
                "minimum": 0,
                "description": "Light intensity measured in lumens."
              },
              "sentAt": {
                "type": "string",
                "format": "date-time",
                "description": "Date and time when the message was sent."
              }
            }
          }
        }
      }
    }
  }
}
```

#### Expected behavior
HTML should be output, this is the case when the hook is disabled, or when my guard is in place.

**Comment by btimby** [comment]
I have a PR here that apparently fixes the issue:

https://github.com/asyncapi/html-template/pull/251

It is likely that I am doing something wrong. However, I inspected the parameter passed into the hook and it has no `asyncapi` property. Further, no other property seems to have `info` or `version` or `_json` properties. The other hooks do not utilize the `asyncapi` property, and thus function.

**Comment by jonaslagoni** [comment]
@btimby is there a specific use-case, that fuels you pre-parse the AsyncAPI document? 🤔 

Pretty sure this will fix your issue:
```
const asyncApiDocument = require('./spec/ws.json');
const generator = new Generator(
  '@asyncapi/html-template',
  null,
  {
    entrypoint: 'index.html',
    output: 'string',
    // There seems to be a bug in this hook.
/*    disabledHooks: {
      'generate:before': [
        'generate:before',
      ],
    },*/
    templateParams: {
      singleFile: true,
    }
  }
);
generator.generate(asyncApiDocument).then((html) => console.log(html));
```

**Comment by btimby** [comment]
@jonaslagoni Thanks for the reply.

Indeed, the first solution I tried is identical to your first example, however, when doing that, I get the following exception:

```javascript
(node:1957811) UnhandledPromiseRejectionWarning: Error: Parameter "asyncapiDocument" must be an AsyncAPIDocument object.
    at Generator.generate (/home/btimby/Code/node_modules/@asyncapi/generator/lib/generator.js:167:64)
    at Object.<anonymous> (/home/btimby/Code/test.js:23:11)
    at Module._compile (internal/modules/cjs/loader.js:1138:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1158:10)
    at Module.load (internal/modules/cjs/loader.js:986:32)
    at Function.Module._load (internal/modules/cjs/loader.js:879:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:71:12)
    at internal/main/run_main_module.js:17:47
(node:1957811) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 2)
(node:1957811) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

The second example is undesirable to me, because I use the schema with multiple libraries, document generation is but a single step. I strongly prefer to import the json schema one time and utilize it multiple times, rather than each individual library parsing a json or yaml file separately. I also perform manipulations on the schema, loading directly from a file is not desirable for my use-case.

The attached script is only meant to reproduce the problem I am experiencing. My actual project is much more complex.

**Comment by btimby** [comment]
FYI, at the referenced line number:

```
if (!(asyncapiDocument instanceof AsyncAPIDocument)) throw new Error('Parameter "asyncapiDocument" must be an AsyncAPIDocument object.');
```

FWIW: I am using swagger / openapi in the same manner as your first example, I am able to pass the imported `.json` schema directly to all of the tools I am using. This would be my preferred approach, as I am attempting to integrate the documentation of my websocket api with that of my rest api.

**Comment by btimby** [comment]
Looking at the unit tests for `html-template`, I came across this:

https://github.com/asyncapi/html-template/blob/master/test/filters/all.test.js#L58

However, when I follow that pattern, I receive the same error.

```javascript
const Generator = require('@asyncapi/generator');
const { AsyncAPIDocument } = require('@asyncapi/parser');
const asyncApiDocument = require('./spec/ws.json');

const generator = new Generator(
  '@asyncapi/html-template',
  null,
  {
    entrypoint: 'index.html',
    output: 'string',
    // There seems to be a bug in this hook.
/*    disabledHooks: {
      'generate:before': [
        'generate:before',
      ],
    },*/
    templateParams: {
      singleFile: true,
    }
  }
);


const doc = new AsyncAPIDocument(asyncApiDocument);
generator.generate(doc).then((html) => console.log(html));
```

```javascript
(node:1965642) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'info' of undefined
    at generate:before (/home/btimby/Code/node_modules/@asyncapi/html-template/hooks/00_changeSpecVersion.js:6:56)
    at /home/btimby/Code/node_modules/@asyncapi/generator/lib/generator.js:792:20
    at Array.map (<anonymous>)
    at Generator.launchHook (/home/btimby/Code/node_modules/@asyncapi/generator/lib/generator.js:789:28)
    at Generator.generate (/home/btimby/Code/node_modules/@asyncapi/generator/lib/generator.js:190:16)
(node:1965642) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 3)
(node:1965642) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**Comment by btimby** [comment]
TBH, I am confused how this hook could EVER work. The generator class does not define a property named `asyncapi` so I don't see how this could ever be destructured from the hook argument.

**Comment by jonaslagoni** [comment]
> TBH, I am confused how this hook could EVER work. The generator class does not define a property named `asyncapi` so I don't see how this could ever be destructured from the hook argument.

It does - https://github.com/asyncapi/generator/blob/master/docs/api.md#generatorasyncapi--asyncapidocument

Trying to see where all this goes wrong 🧐

**Comment by jonaslagoni** [comment]
Think I found it, 2 seconds.

**Comment by btimby** [comment]
@jonaslagoni Thanks for looking. I know the docs mention that property, but at runtime it does not exist for me, and grepping the code does not reveal where it is defined. I typically ignore docs and look at code instead.

**Comment by jonaslagoni** [comment]
> @jonaslagoni Thanks for looking. I know the docs mention that property, but at runtime it does not exist for me, and grepping the code does not reveal where it is defined. I typically ignore docs and look at code instead.

It's a good thing to do because it does not include it 😄 Not when you use it as a library (when used through the CLI it works fine because it calls different functions. It is a bug with the generator itself.

For your workaround you can do:
```
const asyncApiDocument = require('./streetlight.json');
const Generator = require('@asyncapi/generator');
const generator = new Generator(
  '@asyncapi/html-template',
  null,
  {
    entrypoint: 'index.html',
    output: 'string',
    templateParams: {
      singleFile: true,
    }
  }
);

generator.generateFromString(JSON.stringify(asyncApiDocument)).then((html) => console.log(html));
```

I dont have time to fix the bug in the generator, if you do feel free to take charge here 🙂 

Generate - https://github.com/asyncapi/generator/blob/951e902062c597efd87b6516d75499275bb9b459/lib/generator.js#L166 does not at any point set the `this.asyncapi` variable. All the other entry functions call `generateFromString` which does set it - https://github.com/asyncapi/generator/blob/951e902062c597efd87b6516d75499275bb9b459/lib/generator.js#L263

**Comment by btimby** [comment]
OK, that makes sense. I will close my other PR and open one to fix this issue.

**Comment by magicmatatjahu** [comment]
@btimby As I see you fixed problem in the https://github.com/asyncapi/generator/pull/631 PR, so I will close the issue. Feel free to reopen and comment if you think that issue is still relevant :)
