### ISSUE TITLE
TypeError: channel.servers is not a function

### ISSUE THREAD

**Issue by pioneer2k** [asyncapi/html-template#264]
#### Describe the bug
We are using a combination of "GitHub Actions" Action asyncapi/github-action-for-generator@v1.0.35 with template '@asyncapi/html-template@0.23.5' for some weeks now. Everything worked fine. Since yesterday we get in error in our GitHub Actions Pipelines:
Error: (/home/runner/work/_actions/asyncapi/github-action-for-generator/v1.0.35/node_modules/@asyncapi/html-template/template/index.html) [Line 7, Column 57]
  TypeError: channel.servers is not a function

The error occurs with html-template v0.23.9 as well. We had to go back to v0.20.1 as a workaround.
Using a newer version of asyncapi/github-action-for-generator is not possible due to another issue: https://github.com/asyncapi/github-action-for-generator/issues/127

#### How to Reproduce
use the GitHub Action with thml-template 0.23.5 like this:

      - name: Generating HTML from AsyncAPI document
        uses: asyncapi/github-action-for-generator@v1.0.35
        with:
          template: '@asyncapi/html-template@0.23.5' 
          filepath: src/main/resources/asyncapi.yml
          parameters: baseHref=/customer-context-asyncapi-generated-html/
          output: asyncapi/customer-context-asyncapi-generated-html

#### Expected behavior
no error

**Comment by derberg** [comment]
`channel.servers` is used starting from `v0.23.9` because of asyncapi 2.2 release so this is super weird that in version `v0.23.5` you get this error too 🤔

**Comment by derberg** [comment]
what I'm trying to say is, the issue would make sense only if you use `v0.23.9` because generator in the action is not yet updated with latest version 🤔

**Comment by PB-TW** [comment]
I have the same error for the same version combination. It started appearing yesterday afternoon.

**Comment by magicmatatjahu** [comment]
It appears that the generator is using an older version, while the template itself downloads the latest version of `react-component` -> https://github.com/asyncapi/html-template/blob/master/package.json#L37

**Comment by magicmatatjahu** [comment]
Created PR with fix - https://github.com/asyncapi/asyncapi-react/pull/445 We shouldn't wait for fixed generator action.

**Comment by magicmatatjahu** [comment]
@pioneer2k @PB-TW Please use the latest version of html-template `0.23.10`. Make sure that you use this version, and let us know about problems.

**Comment by magicmatatjahu** [comment]
Thank your for info! As if there are any problems please ping me in this issue. I will close the issue.
