### ISSUE TITLE
Describe how to use template in other environments

### ISSUE THREAD

**Issue by vanyakosmos** [asyncapi/html-template#300]
#### Reason/Context

For some project it would be convenient to be able to generate html template for asyncapi on the fly, but right now it is not clear how to do this. 

On the fly docs generation is literally the only way I use openapi spec. 

I tried to integrate asyncapi into python-fastapi application. Found some outdated lib which used old html-template and jinja2 templating engine and I tried to apply similar approach on new template but failed miserably, probably because template tags/filters are for js, and it will be hard to repurpose them in jinja2 without lots of code duplication.

#### Description

I don't know how openapi does this, but i'm 50% sure that their template can generate html by simply inserting json-spec either by unknown magic or by inserting spec-url into search bar.

**Comment by derberg** [comment]
@vanyakosmos Welcome! I'd love to help you but need some clarification. When you say "on the fly" you mean "on request". That you can have a UI like studio.asyncapi.io where you provide the AsyncAPI document and automatically get documentation generated? Example preview with hidden editor -> https://studio.asyncapi.com/?url=https://raw.githubusercontent.com/asyncapi/spec/master/examples/streetlights-kafka.yml&readOnly=true

If I get it right, you should have a look at this project https://github.com/asyncapi/asyncapi-react/tree/next and lemme know if this is what you need.

**Comment by magicmatatjahu** [comment]
@vanyakosmos Hello! As derberg wrote, for rendering on the fly you can use our https://github.com/asyncapi/asyncapi-react/tree/next component. One of our contributors creates `asynction` framework based on python and did this to render spec https://github.com/dedoussis/asynction/blob/main/asynction/templates/index.html.j2 You can reuse that logic. Please also check documentation for rendering spec on the simple html page https://github.com/asyncapi/asyncapi-react/blob/next/docs/usage/standalone-bundle.md#usage-in-html-webpage Let us if it fit for you :)

**Comment by magicmatatjahu** [comment]
@vanyakosmos Any feedback? :)
