### ISSUE TITLE
Package will not install on an Apple Silicon M1 processor based machines.

### ISSUE THREAD

**Issue by dsandor** [asyncapi/html-template#348]
#### Describe the bug
Package will not install on an Apple Silicon M1 processor based machines. This is ultimately due to the version of pupeteer being used. 

#### How to Reproduce
On an M1 / Apple Silicon arm64 machine simply run the following command:

`npm i -g @asyncapi/html-template @asyncapi/generator`

```
❯ npm i -g @asyncapi/html-template @asyncapi/generator
npm WARN deprecated har-validator@5.1.5: this library is no longer supported
npm WARN deprecated mkdirp@0.3.5: Legacy versions of mkdirp are no longer supported. Please update to mkdirp 1.x. (Note that the API surface has changed to use Promises in 1.x.)
npm WARN deprecated mkdirp@0.3.5: Legacy versions of mkdirp are no longer supported. Please update to mkdirp 1.x. (Note that the API surface has changed to use Promises in 1.x.)
npm WARN deprecated uuid@3.4.0: Please upgrade  to version 7 or higher.  Older versions may use Math.random() in certain circumstances, which is known to be problematic.  See https://v8.dev/blog/math-random for details.
npm WARN deprecated request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
npm WARN deprecated puppeteer@5.5.0: Version no longer supported. Upgrade to @latest
npm ERR! code 1
npm ERR! path /Users/dsandor/.nvm/versions/node/v16.15.0/lib/node_modules/@asyncapi/html-template/node_modules/puppeteer
npm ERR! command failed
npm ERR! command sh -c node install.js
npm ERR! The chromium binary is not available for arm64:
npm ERR! If you are on Ubuntu, you can install with:
npm ERR!
npm ERR!  apt-get install chromium-browser
npm ERR!
npm ERR! /Users/dsandor/.nvm/versions/node/v16.15.0/lib/node_modules/@asyncapi/html-template/node_modules/puppeteer/lib/cjs/puppeteer/node/BrowserFetcher.js:112
npm ERR!             throw new Error();
npm ERR!             ^
npm ERR!
npm ERR! Error
npm ERR!     at /Users/dsandor/.nvm/versions/node/v16.15.0/lib/node_modules/@asyncapi/html-template/node_modules/puppeteer/lib/cjs/puppeteer/node/BrowserFetcher.js:112:19
npm ERR!     at FSReqCallback.oncomplete (node:fs:198:21)

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/dsandor/.npm/_logs/2022-05-12T12_53_42_700Z-debug-0.log
```

Executing the puppeteer dependency by itself using the latest version appears to work.

```
❯ npm i -g puppeteer@latest

added 58 packages, and audited 59 packages in 4s

8 packages are looking for funding
  run `npm fund` for details

found 0 vulnerabilities
```

#### Expected behavior

Package should install.

**Comment by derberg** [comment]
@dsandor is it still possible to generate PDF after puppeteer update?

**Comment by magicmatatjahu** [comment]
@dsandor Hi! Let us know about Łukasz's question and we will merge fix https://github.com/asyncapi/html-template/pull/351

**Comment by dsandor** [comment]
Can you give me a pointer on how to test this?  I tried `npm install` and providing the pull request path.  I can confirm that the version of puppeteer you added to the package.json does install on my M1.  But I can't figure out how to test the PR :)

**Comment by magicmatatjahu** [comment]
@dsandor The easiest way is to download the zip (or git if you like) of my branch https://github.com/magicmatatjahu/html-template/tree/fix/update-pupetter, extract, install the dependencies by `npm install` and generate the documentation via

```bash
ag {YOUR_ASYNCAPI_FILE} ./ -o ./output
```

(it should be run inside extracted folder, because second argument `./` points to this extracted folder with template)

I could do it myself, but you can probably guess that I don't have M1 😄  Let me know about problems.

> Also, I tried with the markdown generator and that does in fact work.

Yeah, `markdown-template` doesn't have a `puppeter` dep.

**Comment by magicmatatjahu** [comment]
@dsandor Hello! We just published `0.24.10` version with updated puppeter. Let us know about problems!

**Comment by dsandor** [comment]
@magicmatatjahu Works perfectly!  Thanks for the quick turn around.

**Comment by magicmatatjahu** [comment]
@dsandor Hah, It wasn't that quick, but I'm glad it works! :)
