### ISSUE TITLE
Add timeout parameter to use in pdf generation

### ISSUE THREAD

**Issue by llobetrj** [asyncapi/html-template#387]
#### Reason/Context
Please try answering few of those questions
- Why we need this improvement?
- How will this change help?
- What is the motivation? 
Some times the pdf generation consumes more than the default timeout used in puppeteer that is 30 segs. So this change will allow to generate the PDF's that consumes more time than the default.

#### Description
Please try answering few of those questions
- What changes have to be introduced?
- Will this be a breaking change?
- How could it be implemented/designed?

I will add a templateParam to the package.json file as well as handling for said parameter in the HTML template with the default value of 30000 ms. Add the timeout parameter in Page.pdf with the new parameter value.
I will add documentation for this new parameter.

This will not be a breaking change. No real design is necessary.

**Comment by magicmatatjahu** [comment]
@llobetrj if you will have a problem let me know!
