### ISSUE TITLE
Use message.uid() rather than optional message.name()

### ISSUE THREAD

**Issue by schw4rzlicht** [asyncapi/html-template#39]
#### Reason/Context
More a cleanup proposal/discussion towards how message names are rendered in the resulting HTML according to [this PR](https://github.com/asyncapi/markdown-template/pull/28) in the `markdown-template`.

#### Description

https://github.com/asyncapi/html-template/blob/03eb7dd360d19f85bd143bd7ef643c8d11e04496/partials/message.html#L11-L20

This block would need to be changed to use `msg.uid()`. When to actually include it should be discussed. With the mentioned PR in `markdown-template`, using the `name` property in messages is optional since the template falls back to the property-name of the message-object. Would be nice to see a similar behavior in the HTML template as well.

**Comment by derberg** [comment]
Do you mean removing `message.title()` too? or just replace `message.name()` with `message.uid()`?

I like we treat title here as a first-level citizen, would be nice to have it in a place where you just contributed  in markdown template

**Comment by schw4rzlicht** [comment]
Probably replacing `message.name()` with message.uid()` does the job already.

**Comment by derberg** [comment]
yeap, I wanted to confirm you do not want to remove the title 😄 
you wanna openup a PR for that?
