### ISSUE TITLE
Minimum Value is not shown

### ISSUE THREAD

**Issue by Fettpet** [asyncapi/html-template#411]
#### Describe the bug
In the given example, I create a simple message with two values, a integer and a number. Both are restricted inside a range. The auto generated documentation shows only the maximum value. The minimum value is ignored.

#### How to Reproduce

1. I create [test AsyncAPI Description](https://gist.github.com/Fettpet/b0921dab720b3665ebee2066969535e3). 
2. I called 
`asyncapi generate fromTemplate minimum.yml @asyncapi/html-template -o doc_min -p singleFile=true `

I get the following documentation, where the minimum value is missing 
![image](https://user-images.githubusercontent.com/3716466/217569774-87bc039c-e28e-477d-9b12-7bf9062d3996.png)

#### Expected behavior
I expect that the minimum value is shown, if they are provided.

**Comment by magicmatatjahu** [comment]
@Fettpet Hi! You have typo bug `minimium` -> `minimum` 😄

**Comment by Fettpet** [comment]
@magicmatatjahu Thanks a lot. This solves the issue. Sorry for troubles :)

**Comment by magicmatatjahu** [comment]
@Fettpet No problem! :)
