### ISSUE TITLE
Studio AsyncAPI: Cannot read properties of null - Issue with property named "message"

### ISSUE THREAD

**Issue by NickManit** [asyncapi/html-template#416]
#### Describe the bug
I am currently getting the following error from studio.asyncapi.com when I use asyncapi version >=2.4.0:

Error thrown during AsyncAPI document validation. Name: TypeError, message: Cannot read properties of null (reading 'oneOf'), stack: TypeError: Cannot read properties of null (reading 'oneOf') at $.channels.*.[publish,subscribe][?(@property === "message" && @.oneOf == void 0)] (eval at value (https://studio.asyncapi.com/static/js/main.13c62293.js:2:4582376), <anonymous>:561:71) at eval (eval at value (https://studio.asyncapi.com/static/js/main.13c62293.js:2:4582376), <anonymous>:634:98) at o (https://studio.asyncapi.com/static/js/main.13c62293.js:2:4607027) at a (https://studio.asyncapi.com/static/js/main.13c62293.js:2:4607290) at o (https://studio.asyncapi.com/static/js/main.13c62293.js:2:4607056) at a (https://studio.asyncapi.com/static/js/main.13c62293.js:2:4607290) at o (https://studio.asyncapi.com/static/js/main.13c62293.js:2:4607056) at a (https://studio.asyncapi.com/static/js/main.13c62293.js:2:4607227) at o (https://studio.asyncapi.com/static/js/main.13c62293.js:2:4607056) at a (https://studio.asyncapi.com/static/js/main.13c62293.js:2:4607290)

#### How to Reproduce
Simply change the version of asyncapi from 2.3.0 to 2.4.0 or above, and the error I mentioned will be thrown:

```
asyncapi: 2.3.0
info:
  title: Customer Message
  version: 1.0.0
channels:
  /test/url/customer-message:
    publish:
      operationId: customer-message
      message:
        name: customer-message
        contentType: application/json
        payload:
          $ref: '#/components/schemas/CustomerMessage'
        examples:
          - payload:
              customerId: "123"
              message: null
          - payload:
              customerId: "123"
              message: string
components:
  schemas:
    CustomerMessage:
      type: object
      properties:
        customerId:
          nullable: false
          type: string
        message:
          nullable: true
          type: string
```

#### Expected behavior
As far as I understood, this error is related with two things:
1. The name of the "message" property. If I change the name to "msg", it works fine.
2. The example where message: null. If I set a different value, then it also works fine.

However, I do not think this is the normal behaviour. I guess the expected behaviour is to accept this structure and not throw an error. Could someone please clarify?

**Comment by derberg** [comment]
no response, I guess my previous comment solved the bug
