### ISSUE TITLE
Sidebar partial use document root tags, not operation tags

### ISSUE THREAD

**Issue by sebastian-palma** [asyncapi/html-template#42]
Currently the sidebar is iterating over each element in `asyncapi.tags()` and checking if that tag name is in the channel tags (publish/subscribe) when they have tags:

```html
{% if channel.publish() and channel.publish().hasTags() and channel.publish() | containTags(categorytags) %}
...
{% endif %}

{% if channel.subscribe() and channel.subscribe().hasTags() and channel.subscribe() | containTags(categorytags) %}
...
{% endif %}
```

But that means you need strictly to have the same tags you have in every channel, at the root of the document. Otherwise, they're all rendered as Untagged.

In an example code like [this](https://gist.github.com/sebastian-palma/eeb128d38b2769d7ce12f8f033b0da15) (see both `foo` and `bar` tags in `smartylighting/streetlights/1/0/event/{streetlightId}/lighting/measured` and `smartylighting/streetlights/1/0/action/{streetlightId}/turn/on` respectively), running the generator with the `sidebarOrganization` equals to `byTags` would generate the sidebar like this:

![Screen Shot 2020-06-04 at 12 55 23](https://user-images.githubusercontent.com/11888191/83743299-35095a80-a663-11ea-950c-f773188c2da3.png)

And if you add the tags to the root of the document as:

```yaml
...
tags:
  - name: foo
  - name: bar
```

The sidebar is generated like this:

![Screen Shot 2020-06-04 at 13 01 30](https://user-images.githubusercontent.com/11888191/83743610-a0532c80-a663-11ea-94c5-b0db2bfae244.png)

Foo and Bar have no channels, they're placed under the Untagged _label_.

It seems the logic of the sidebar regarding tags was written taking in mind that every tag under every channel must be in the root tags, so they can be grouped by iterating the root tags and then associating them as long as the channel tags contain the root tag from the iteration, which is okay because it works, but it'd force us to duplicate the place where we add the tags; once in the root and once for each channel having tags.

**Comment by derberg** [comment]
@fmvilas do you recall why `asyncapi.tags()` was added to the logic that builds tag left nav? when I look at it, it seems to me it could never work

**Comment by fmvilas** [comment]
This was the initial issue: https://github.com/asyncapi/generator/issues/69. It's another way to structure the sidebar.

**Comment by sebastian-palma** [comment]
Do we consider adding a way to render tags without having them in the root of the document? Or do we close the issue in favor of keeping the current functioning @fmvilas, @derberg?

**Comment by derberg** [comment]
tbh I would not like to force spec writer to add tags to the root only to satisfy the html-template.

I understand that current implementation is done like this as it was just easier at that time to implement, so the user can "model" the navigation structure with the root tags.

I like the approach that root tags are not needed, that we just have a filter that first iterates over all channels to build an array of all available tags, and then builds the nav accordingly, best by putting tags in alphabetical order.

but seems like current functionality is used so would be bad to break it, which means best would be to have both 🤔 but "the new functionality applies only if there are no root tags" would not be cool, so what, another parameter?

**Comment by sebastian-palma** [comment]
I think that the easier for this is to add a new parameter, and as you say @derberg, just map every operation tag using filters. Don't know what you guys think, should we take this?

**Comment by derberg** [comment]
let's do it, @fmvilas as you were involved in the first version of the nav building, any objections or different ideas? we do not want to offend you ❤️ or do we :trollface:

**Comment by fmvilas** [comment]
Haha! I'm fine as long as it makes sense. Pinging @rv0 as he was the one suggesting this feature.

**Comment by rv0** [comment]
thanks @fmvilas for the heads up
No objections here, seems like the way forward
