### ISSUE TITLE
Add raw asyncapi.json file download to HTML Page

### ISSUE THREAD

**Issue by rez10191** [asyncapi/html-template#428]
We're using the asyncapi/html-template to generate documentation about our Async API we provide for customers.  The HTML page is served on our website.  We would like to make it easy for other developers to go to the site and download the raw `asyncapi.json` file the site was based on.  We typically build and deploy this page as part of our autobuild process.  

I realize an option would be to also copy the input file over to the web server and include a link in the documentation, but we've also had good luck with the `-p singleFile=true` option for sending the documentation to customers directly.

Thanks for your consideration.

**Comment by derberg** [comment]
@rez10191 can you specify what you need exactly? like you want generated docs to contain a kind of button to download or something?

**Comment by derberg** [comment]
no more details provided 😞 closing
can't proceed especially that it is not clear how could it work with `singleFile` when user expects single file
