### ISSUE TITLE
AsyncAPI spec v3 support in HTML-template

### ISSUE THREAD

**Issue by jonaslagoni** [asyncapi/html-template#430]
### Reason/Context
This Issue is used to track changes needed to support AsyncAPI v3. As a code owner, please edit this list of TODO tasks in order to properly track the progress 🙂 Once this issue is closed it means that v3 is now fully supported in this library.  

### Scope
- [x] Migrate to the new JS parser API
- [ ] https://github.com/asyncapi/asyncapi-react/issues/733

**Comment by fmvilas** [comment]
/progress 90 Just waiting for https://github.com/asyncapi/html-template/pull/448 to get merged.

**Comment by jonaslagoni** [comment]
/progress 80 waiting for parser to be released to update dependencies and then it should work out the box
