### ISSUE TITLE
Slack invitation link does not work anymore.

### ISSUE THREAD

**Issue by kontrafiktion** [asyncapi/html-template#445]
#### Describe the bug
Tried to use the Slack invitation link to ask a question before submitting an issue (not this one), but the link seems to be stale

#### How to Reproduce
Go to: https://github.com/asyncapi/html-template/issues and click on "New Issue". The following page is shown.

- Screenshots
![CleanShot 2023-09-06 at 16 36 12](https://github.com/asyncapi/html-template/assets/198502/6ab96bb9-c26b-4d1c-91ac-ff980d17bdd2)

Now click on "Open" in the "Slack" row and you get

![CleanShot 2023-09-06 at 16 39 50](https://github.com/asyncapi/html-template/assets/198502/f3afb70a-e137-4555-b877-5eb3bdcf084d)

#### Expected behavior

Either remove the Slack link altogether or add one that works.

**Comment by derberg** [comment]
@kontrafiktion thanks for the issue. Can you please try again. I see that people are still joining our Slack, like yesterday was one person.

The link that we use everywhere is https://www.asyncapi.com/slack-invite/ that at the moment redirects to https://join.slack.com/t/asyncapi/shared_invite/zt-1vd6bk0j5-54Kh5C1kM6y0yxux1WikrA which [I remember I've set](https://github.com/asyncapi/website/pull/1672) as a permanent never expire invite

**Comment by kontrafiktion** [comment]
I still get "The link is no longer active"

**Comment by derberg** [comment]
@kontrafiktion can you please try https://join.slack.com/t/asyncapi/shared_invite/zt-2329g7esz-jPKWhnRBX0NKJMK4gatqKQ

**Comment by kontrafiktion** [comment]
works!

**Comment by derberg** [comment]
thanks for the confirmation! [Slack is very confusing](https://twitter.com/derberq/status/1701526025543336099)

weird, by default you should be added to all default channels (that start with a number)

**Comment by kontrafiktion** [comment]
ah, now I see 
![CleanShot 2023-09-12 at 11 37 40](https://github.com/asyncapi/html-template/assets/198502/629c00e1-2933-4d10-b21c-0b35bccbcc41)

**Comment by derberg** [comment]
@kontrafiktion thanks a lot again. Public links fixed in production
