### ISSUE TITLE
1.0.0 reverses pub and sub

### ISSUE THREAD

**Issue by fractal-joe** [asyncapi/html-template#453]
#### Describe the bug

renders pub for sub and sub for pub

**Comment by skonik** [comment]
Also I noticed that anchors now have wrong links and clicking on channels/messages doesn't move your page view to that specific message(due to broken anchors)

**Comment by derberg** [comment]
please folks provide example AsyncAPI document and specify, which parts we should check exactly to replicate

**Comment by skonik** [comment]
@derberg

I've submitted similar issue to asyncapi-react repository. 
https://github.com/asyncapi/asyncapi-react/issues/815

In short: you can notice that `subscribe` definition rendered as `pub` tag.
<img width="1726" alt="Screenshot 2023-10-12 at 14 08 43" src="https://github.com/asyncapi/html-template/assets/50069473/7b5376fd-3cbc-450e-bc73-a7dfb88ebbf6">
