### ISSUE TITLE
[Docs Bug 🐞 report]: blank html page

### ISSUE THREAD

**Issue by badien** [asyncapi/html-template#460]
### Describe the bug you found in AsyncAPI Docs.

open html file on browser --> blank page --> no any error script from browser
using tools:
 - Async API version 2.5.0 / 2.6.0
 - @aysyncapi/generator version 1.14.1
 - @asyncapi/html-template version: 1.0.0 --> old version 0.28.0 --> page is ok but wrong id between div tab and side bar button --> version 0.28.4 normally
 - nodejs 18
 - npm 9.8.1
 - OS: Mac OS Sonoma 14.0
 
Please check, thanks.

### Attach any resources that can help us understand the issue.

command line:
 - ag @asyncapi/html-template --force-write -o ${targetTempPath} -p outFilename=${targetFile} -p singleFile=true

### Code of Conduct

- [x] I agree to follow this project's Code of Conduct

**Comment by jonaslagoni** [comment]
Thanks for the detailed report @badien, lets use https://github.com/asyncapi/html-template/issues/456 to triage.

**Comment by derberg** [comment]
closing so all discussion happens in one issue in https://github.com/asyncapi/html-template/issues/456
