### ISSUE TITLE
Even 0.28 can't create correct anchors, 2.0 pubs instead of subs

### ISSUE THREAD

**Issue by TertiumOrganum1** [asyncapi/html-template#464]
#### Describe the bug
When using without specifying version it uses broken 2.0 (pubs instead of subs, broken links).
1.0 shows nothing as people said already.
When I specify 0.28.3 it builds html but anchors with operations are broken.

#### How to Reproduce
Here is api file and doc result.
[asyncapi.zip](https://github.com/asyncapi/html-template/files/13518811/asyncapi.zip)

#### Expected behavior
Should work at least like vscode "asyncapi preview" extention

**Comment by christianrowlands** [comment]
It looks like this bug is the same as the one I reported [here](https://github.com/asyncapi/html-template/issues/463). Glad to know it is not just me having the problem.

**Comment by BTOdell** [comment]
The bugs are coming from this repo: https://github.com/asyncapi/asyncapi-react

And honestly, where is the quality control? It's surprising how anyone would release something in this broken of a state.

**Comment by derberg** [comment]
@TertiumOrganum1 thanks for reporting the issue. Fix for pub/sub is out already. In case of anchors in operations there is an issue in https://github.com/asyncapi/asyncapi-react/issues/822 so I will close this issue as a duplicate so we stay focused.

@BTOdell sorry for the situation. It is super hard to keep good quality with such a low number of maintainers we have here at AsyncAPI Initiative. Event-driven architectures are used everywhere. There are also 100s of companies that like to use our open source tool, even some push PRs, but unfortunately not many are open to share ownership of code. You can have a look at my presentation from this year where I openly address that pain with AsyncAPI community -> https://youtu.be/fuqMIlnzrv4?t=638. If you or your company or anyone you know would like to help, or would even like to help with `react-component` maintenance - I'm happy to hop on a call 🙏🏼

**Comment by derberg** [comment]
closing this one as per the comment I did in december
