### ISSUE TITLE
Operations anchors don't navigate to the corresponding document area

### ISSUE THREAD

**Issue by ValeryShvyndzikau** [asyncapi/html-template#485]
Hi AsyncAPI team,
It looks like "Operations" anchors don't navigate to the corresponding section within the document. Could you please take a look
![image](https://github.com/asyncapi/html-template/assets/1850133/d0b6725c-8bd9-4d60-ba6a-19921591ecfe)

**Comment by bjhartin** [comment]
@ValeryShvyndzikau I encountered this, and until they have a fix, there is an easy workaround:

```bash
sed -i "s/operation-send/operation-publish/g"  output/contract/index.html 
sed -i "s/operation-receive/operation-subscribe/g" output/contract/index.html
```
