### ISSUE TITLE
Example override for ref schema object not working

### ISSUE THREAD

**Issue by christianrowlands** [asyncapi/html-template#495]
**Note**: Issue #463 had two bugs mentioned in it, so I am creating this ticket to pull one of the bugs out so it can be tracked individually (my bad for lumping them together).

#### Describe the bug
The example that I set for a field is not being used in the generated HTML when using a $ref to a schema.

I have published my AsyncAPI HTML docs on [public URL](https://messaging.networksurvey.app/), so you can see both issues on that site.

if you look at any of the Payload schemas, they all have a messageType field. A couple months ago I noticed that the override description and example stopped working. For example, with the GSM Record under the gsm_message operation, the messageType should be The type of message, must be GsmRecord. since that is what I set it to [here in the yaml spec](https://github.com/christianrowlands/network-survey-messaging/blob/b941e4ce3242d705958f52b421f9f1f6fd796b90/src/main/asyncapi/network_survey_messaging.yaml#L306).

In addition, the example is also not being overridden as expected. I set it to GsmRecord [here in the yaml spec](https://github.com/christianrowlands/network-survey-messaging/blob/b941e4ce3242d705958f52b421f9f1f6fd796b90/src/main/asyncapi/network_survey_messaging.yaml#L307) but in the generated doc it shows up as string. Below is a screenshot of the linked generated HTML:

![image](https://github.com/asyncapi/html-template/assets/8020686/cb369312-ea8b-4d2c-ab09-9c00da0d680a)

#### How to Reproduce
For reproducing the issue, you can either use the [full yaml spec](https://github.com/christianrowlands/network-survey-messaging/blob/b941e4ce3242d705958f52b421f9f1f6fd796b90/src/main/asyncapi/network_survey_messaging.yaml) I have linked to that is in my GitHub repo, or you can use this condensed version I made below. I typically use the docker container for asyncapi to generate the yaml. Something like:

docker run --rm -it -v ${PWD}/asyncapi/test.yaml:/app/test.yaml -v ${PWD}/testdoc:/app/output asyncapi/generator:1.17.0 /app/test.yaml @asyncapi/html-template@2.1.0 -o /app/output --force-write

```yaml
asyncapi: 2.6.0
info:
  title: Test API
  version: 0.13.1
  description: >
    A test doc for reproducing an issue
  license:
    name: Apache 2.0
    url: 'https://www.apache.org/licenses/LICENSE-2.0'
servers:
  mosquitto:
    url: 'mqtt://test.mosquitto.org'
    protocol: mqtt
defaultContentType: application/json
channels:
  gsm_message:
    description: >-
      The gsm_message topic/channel is where GSM survey records can be
      published. For MQTT, set the MQTT topic as "gsm_message" and then publish
      a JSON message representing a GSM survey record in the format defined
      below.
    publish:
      message:
        $ref: '#/components/messages/gsmRecord'
components:
  messages:
    gsmRecord:
      name: GsmRecord
      title: GSM Record
      summary: >-
        Represents information recorded about a GSM tower at a particular time
        and geographic location.
      contentType: application/json
      payload:
        $ref: '#/components/schemas/gsmRecordPayload'
  schemas:
    gsmRecordPayload:
      type: object
      required:
        - version
        - messageType
        - data
      properties:
        version:
          $ref: '#/components/schemas/version'
        messageType:
          $ref: '#/components/schemas/messageType'
          description: 'The type of message, must be GsmRecord.'
          example: GsmRecord
        data:
          type: object
          description: The payload of this message that contains all the message data.
          required:
            - deviceTime
          properties:
            deviceTime:
              $ref: '#/components/schemas/deviceTime'
    version:
      type: string
      description: >-
        The version number of the Network Survey Messaging API that this message
        is based off of.
      example: 0.13.1
    messageType:
      type: string
      description: >-
        The type of this message. This value must match the message name or the
        message will not be interpreted correctly.
    deviceTime:
      type: string
      format: date-time
      description: >-
        The timestamp of when this message was created in milliseconds formatted
        as an [RFC3339
        date-time](https://xml2rfc.tools.ietf.org/public/rfc/html/rfc3339.html#anchor14).
        For example, `'1996-12-19T16:39:57-08:00'`.
```

#### Expected behavior
The expected behavior is

1. That the messageType value in the generated example json code block should have a value of `GsmRecord`.
2. That the messageType description for GSM Record should be: `The type of message, must be GsmRecord.`

**Comment by derberg** [comment]
seems to be completed discussion

@christianrowlands feel free to open a separate issue if you have further questions
