### ISSUE TITLE
tags not rendered in Message Object

### ISSUE THREAD

**Issue by naderafshari** [asyncapi/html-template#5]
Tags are rendered in Operations Objects (at the bottom of the section as dark boxes) but they do not seem to be rendered for Message objects. Attached is a screenshot of using tags in a message.

![asyncAPIplayground1](https://user-images.githubusercontent.com/18668042/78948488-5a238780-7a7d-11ea-9d53-79b35fb22955.png)

**Comment by derberg** [comment]
@naderafshari how do you see it renders, I quickly mocked something like
<img width="505" alt="Screenshot 2020-04-12 at 19 14 13" src="https://user-images.githubusercontent.com/6995927/79075235-e0e09a80-7cf1-11ea-9af9-6650961c9360.png">

on hover over `test1` you would see a tooltip with description. What do you think?

**Comment by naderafshari** [comment]
Looks great to me thank you @derberg

**Comment by derberg** [comment]
@naderafshari please have a look and test this PR https://github.com/asyncapi/html-template/pull/8

**Comment by derberg** [comment]
Fixed by https://github.com/asyncapi/html-template/pull/8
