### ISSUE TITLE
[BUG] Scalar types are shown as expandable when they aren't

### ISSUE THREAD

**Issue by fmvilas** [asyncapi/html-template#50]
#### Describe the bug
Scalar types like `String`, `Int`, `Boolean`, etc. are shown as "expandable" when there's nothing to "expand".

![](http://g.recordit.co/CYvgxXShoQ.gif)

#### How to Reproduce
Check out [playground.asyncapi.io]() with Streetlights example.

#### Expected behavior
They shouldn't show the "expand" arrow button.

**Comment by stevenj** [comment]
Yes, this also seems relatively new, i didn't notice it until i upgraded the HTML generator yesterday.

**Comment by derberg** [comment]
It might be related to recent refactoring in filters, and changes to `isExpandable` filter -> https://github.com/asyncapi/html-template/blob/master/filters/all.js#L3-L22

This is the logic responsible for adding the chevron svg -> https://github.com/asyncapi/html-template/blob/master/partials/schema-prop.html#L11-L16

**Comment by derberg** [comment]
video about the issue https://youtu.be/Iqs_2BiNEEo?t=726

**Comment by gabrielclaudino** [comment]
Hey, I can help with this. Can you assign to me?

**Comment by derberg** [comment]
@gabrielclaudino done. Good luck. In case ya need help write here or join live stream on Tuesday

**Comment by gabrielclaudino** [comment]
Ok 👍
