### ISSUE TITLE
HTML generation of message with protobuf schema does not work

### ISSUE THREAD

**Issue by mfroberg** [asyncapi/html-template#518]
#### Describe the bug
I have an Async API v3 document where the message schema is Protobuf. The generator fails to produce an HTML output and terminates with an error.

#### How to Reproduce
Use the following Async-api document

```yaml
asyncapi: 3.0.0
info:
  title: 'Hello, Glee!'
  version: 0.1.0
servers:
  websockets:
    host: '0.0.0.0:3000'
    protocol: ws
channels:
  hello:
    address: hello
    messages:
      hello:
        $ref: '#/components/messages/hello'
operations:
  onHello:
    action: receive
    channel:
      $ref: '#/channels/hello'
components:
  messages:
    hello:
      payload:
        schemaFormat: application/vnd.google.protobuf;version=3
        schema: |
          message Hello {
            optional string name = 1;
          }
```

Running AsyncAPI CLI v1.4.11 ...
```
asyncapi generate fromTemplate https://github.com/asyncapi/html-template ./asyncapi-protobuf.yaml
```
... produces the following error:
```
SyntaxError: Unexpected token '<', "
<!DOCTYPE "... is not valid JSON
```

#### Expected behavior
Is to produce an HTML file representation similar to Async API Studio.

Please let me know if you need any more information. Thanks!

**Comment by derberg** [comment]
@mfroberg can you please try again with CLI 1.7.3 ?
also please best use `htmp-template` published to npm, so instead of `https://github.com/asyncapi/html-template` refer to template as `@asyncapi/html-template` and best, to use its specific versions to avoid surprises with new versions `@asyncapi/html-template@2.2.1`
