### ISSUE TITLE
Add necessary scripts that on release will publish transpiled template to npm

### ISSUE THREAD

**Issue by derberg** [asyncapi/html-template#558]
Since we migrated this template to React render engine, the generation time, like in other react templates, got super long

Reason - every time generation is run, TS transpilation runs

This can be solved by publishing templates, like this one, to npm with transpilation files included, so basically no transpilation is needed in runtime - unless explicitly requested.

When you clone this repo, install and run `asyncapi generate fromTemplate ./test/spec/asyncapi_v3.yml ./ --output mydocs --force-write` from root, you will notice a new folder called `__transpiled` - this is the folder we need to make sure is included in package publishing.

This is how generator triggers transpilation -> https://github.com/asyncapi/generator/blob/master/lib/renderer/react.js#L19
Now we need to make sure we have proper script here in template that does the same. This new script needs to be called only by this script -> https://github.com/asyncapi/html-template/blob/master/package.json#L33C6-L33C20

We already have some custom scripts in this repo that run on release -> https://github.com/asyncapi/html-template/blob/master/scripts/copy-sources.js so you just plugin into existing infra.

**Note**
Completion of this task do not mean yet that time of generation will go down. I think that babel that we use in https://github.com/asyncapi/generator-react-sdk/blob/master/src/transpiler/transpiler.ts is already smart and do not regenerate if `__transpiled` dir is already there but yeah, lets see

**Comment by jonaslagoni** [comment]
> Completion of this task do not mean yet that time of generation will go down. I think that babel that we use in https://github.com/asyncapi/generator-react-sdk/blob/master/src/transpiler/transpiler.ts is already smart and do not regenerate if __transpiled dir is already there but yeah, lets see

Pretty sure this is NOT the case 🤔 But I have not tested it

**Comment by aeworxet** [comment]
### Bounty Issue's service comment

Text labels: `bounty/2024-Q2`, `bounty/medium`, `bounty/devops`
First assignment to third-party contributors: [2024-03-22 00:00:00 UTC+12:00](https://time.lol/#2024-03-22T00:00:00+12:00)
End Of Life: [2024-08-31 23:59:59 UTC-12:00](https://time.lol/#2024-08-31T23:59:59-12:00)

@asyncapi/bounty_team

**Comment by derberg** [comment]
@jonaslagoni I only did manual tests and manual eye observation. Only first run is always long, the next ones are super fast - this is why I assume, it looks into transpiled directory first during transpilation

**Comment by utnim2** [comment]
@derberg on it

**Comment by derberg** [comment]
@utnim2 just assigned to you. Good luck and lemme know if you need some more details

**Comment by aeworxet** [comment]
### Bounty Issue's Timeline
|Complexity Level|Assignment date (by GitHub)|Start date (by BP rules)|End date (by BP rules)|Draft PR submission|Final PR submission|Final PR merge|
|----------------|---------------------------|------------------------|----------------------|-------------------|-------------------|--------------|
|Medium          |2024-03-21                 |[2024-04-01](https://time.lol/#2024-04-01T00:00:00+12:00)              |**[2024-05-10](https://time.lol/#2024-05-10T23:59:59-12:00)**        |[2024-04-12](https://time.lol/#2024-04-12T23:59:59-12:00)         |[2024-04-26](https://time.lol/#2024-04-26T23:59:59-12:00)         |**[2024-05-10](https://time.lol/#2024-05-10T23:59:59-12:00)**|

##### Please note that the dates given represent deadlines, not specific dates, so if the goal is reached sooner, it's better.
##### Keep in mind the [responsibility](https://github.com/asyncapi/community/pull/897/files#diff-25ecb20a61754c225d6511ca08d7e7c9a14b9ca5a93e89bd42331e51c9ebf26dR201) for violations of the [Timeline](https://github.com/asyncapi/community/pull/897/files#diff-25ecb20a61754c225d6511ca08d7e7c9a14b9ca5a93e89bd42331e51c9ebf26dR127).

**Comment by derberg** [comment]
PR is merged and will be released but it is not yet completed, we need to now test if things improved as expected

**Comment by derberg** [comment]
had to revert it as there was a wrong configuration in package.json

**Comment by derberg** [comment]
@utnim2 do you plan to open another PR?

**Comment by utnim2** [comment]
@derberg i was out of town for a bit, will open a PR tommorow

**Comment by webbdays** [comment]
if @utnim2 is busy,
can i fix the config and push?

**Comment by utnim2** [comment]
> if @utnim2 is busy, can i fix the config and push the changes?

It is fixed in #583

**Comment by webbdays** [comment]
ok.

**Comment by aeworxet** [comment]
@webbdays
Please do not intervene when the issue is an assigned Bounty Issue and is complying with the [Bounty Issue's Timeline](https://github.com/asyncapi/html-template/issues/558#issuecomment-2013941522).
However, if you have a desire to help and receive a reward for completing a Bounty Issue, you can take a look at the non-assigned Bounty Issues for the calendar quarter round `2024-Q2`:
https://github.com/orgs/asyncapi/projects/36/views/4?sliceBy%5Bvalue%5D=bounty%2F2024-Q2&filterQuery=round%3A%22bounty%2F2024-Q2%22+status%3A%22No+Assignee%22

**Comment by webbdays** [comment]
Thanks.

**Comment by derberg** [comment]
Closing
https://github.com/asyncapi/html-template/pull/583 was done good. Unfortunately it did not solve what I thought it will, but from the requirements point of view, @aeworxet the task is completed

**Comment by derberg** [comment]
actually I did some tests and it added some good value -> https://github.com/asyncapi/generator/issues/521#issuecomment-2032159596

**Comment by aeworxet** [comment]
### Bounty Issue Completed 🎉

@utnim2, please go to the [AsyncAPI page on Open Collective](https://opencollective.com/asyncapi) and submit an invoice for `USD 200.00` with the expense title `Bounty html-template#558`, tag `bounty`, and full URL of this Bounty Issue in the description.
