### ISSUE TITLE
Contact email link is rendered wrong

### ISSUE THREAD

**Issue by rv0** [asyncapi/html-template#56]
#### Describe the bug
The email link in the generated document is wrong.

#### How to Reproduce

Add contact info to the info section

```   
info:
  ...
  contact:
    email: support@asyncapi.org
```   

And render.. The email "link" will be created without "mailto:" prefix, making it a (failing) http link.

#### Expected behavior

The link should be a _mailto:_ link

#### Additional info

The same issue also happens on the playground website.

**Comment by derberg** [comment]
Thanks @rv0 

To anyone who will pick this one up:
- this is where the fix needs to be provided -> https://github.com/asyncapi/html-template/blob/master/partials/introduction.html#L26-L29

**Comment by derberg** [comment]
fixed with #84
