### ISSUE TITLE
[FEATURE] Support AsyncAPI v3.0

### ISSUE THREAD

**Issue by leonid-deriv** [asyncapi/html-template#572]
### Why do we need this improvement?

To support the latest spec version

### How will this change help?

Currently we cannot generate doc for v3

### How could it be implemented/designed?

N/A

### 🚧 Breaking changes

No

### 👀 Have you checked for similar open issues?

- [X] I checked and didn't find a similar issue

### 🏢 Have you read the Contributing Guidelines?

- [X] I have read the [Contributing Guidelines](https://github.com/asyncapi/.github/blob/master/CONTRIBUTING.md)

### Are you willing to work on this issue?

No, someone else can work on it.

**Comment by leonid-deriv** [comment]
When do you plan to support v3?

**Comment by jonaslagoni** [comment]
Already supported in html template v2.

**Comment by leonid-deriv** [comment]
Thank you, should have been more persistent in researching it.

**Comment by leonid-deriv** [comment]
Thank you, should have been more persistent in researching it.
