### ISSUE TITLE
externalDocs are not rendered

### ISSUE THREAD

**Issue by naderafshari** [asyncapi/html-template#6]
It appears that externalDocs is not rendered in any of the Objects - Operations, Message, Tag etc.
The externalDocs object has a description and a url field (no name field). One way to implement this would be to make the description into a hyperlink pointing to the url. Another way would be to render a button showing the name of the parent object (for example, the name of the parent tag - after tag issue https://github.com/asyncapi/html-template/issues/5 is fixed) in the button and pointing to the url and the description showing as text under the button.

**Comment by derberg** [comment]
Please test and review this PR https://github.com/asyncapi/html-template/pull/8
