### ISSUE TITLE
Bindings are ignored

### ISSUE THREAD

**Issue by flokasper** [asyncapi/html-template#60]
#### Describe the bug

I am trying to document my websocket, I am using this [asyncapi.yaml](https://github.com/fmvilas/asyncapi-websockets-example/blob/master/asyncapi.yaml) as reference:
```
asyncapi: 2.0.0-rc2
info:
  title: WebSockets echo server
  version: 1.0.0

servers:
  localhost:
    url: localhost
    protocol: ws

channels:
  /echo:
    bindings:
      ws:
        query:
          type: object
          properties:
            times:
              type: integer
              description: How many times the message should be echoed.
              minimum: 1
        bindingVersion: 0.1.0
    subscribe:
      operationId: onEcho
      message:
        $ref: '#/components/messages/echo'
    publish:
      operationId: sendEcho
      message:
        $ref: '#/components/messages/echo'

components:
  messages:
    echo:
      payload:
        type: string
```

The bindings part never showed up in the generated files

#### How to Reproduce
I used:
- [CLI usage with docker](https://github.com/asyncapi/generator#cli-usage-with-docker)
- [playground](https://playground.asyncapi.io/)

#### Expected behavior
I should see the binding query in the documentation

**Comment by derberg** [comment]
Hi, it is not really a bug but a missing feature. Please have a look at https://github.com/asyncapi/html-template/issues/25

**Comment by flokasper** [comment]
OK, my bad, I should have better checked the other issues

**Comment by derberg** [comment]
no worries, please make a comment there that it is important for you. PRs are also welcomed, Jonas made a good short solution suggestion there
