### ISSUE TITLE
[BUG] generator 2 with html-template does not work

### ISSUE THREAD

**Issue by laat** [asyncapi/html-template#619]
### Describe the bug.

```
npm i -D @asyncapi/generator @asyncapi/html-template
npx asyncapi-generator --force-write --output dist asyncapi.yaml @asyncapi/html-template
```

Gives the error

```
Something went wrong:
Error: This template is not compatible with the current version of the generator (2.0.0). This template is compatible with the following version range: >=1.15.0 <2.0.0.
    at isTemplateCompatible (/Users/n637831/git/astest/node_modules/@asyncapi/generator/lib/templateConfigValidator.js:57:11)
    at module.exports.validateTemplateConfig (/Users/n637831/git/astest/node_modules/@asyncapi/generator/lib/templateConfigValidator.js:30:3)
    at Generator.configureTemplateWorkflow (/Users/n637831/git/astest/node_modules/@asyncapi/generator/lib/generator.js:314:5)
    at async Generator.generate (/Users/n637831/git/astest/node_modules/@asyncapi/generator/lib/generator.js:202:5)
    at async Generator.generateFromFile (/Users/n637831/git/astest/node_modules/@asyncapi/generator/lib/generator.js:503:12)
    at async /Users/n637831/git/astest/node_modules/@asyncapi/generator/cli.js:157:9
```

### Expected behavior

It should probably still work.

### Screenshots

repro: https://github.com/laat/asyncapi-generator-repro

### How to Reproduce

repro: https://github.com/laat/asyncapi-generator-repro

### 🥦 Browser

None

### 👀 Have you checked for similar open issues?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Contributing Guidelines?

- [X] I have read the [Contributing Guidelines](https://github.com/asyncapi/.github/blob/master/CONTRIBUTING.md)

### Are you willing to work on this issue ?

None

**Comment by derberg** [comment]
PR is opened https://github.com/asyncapi/html-template/pull/615 but we need to wait for CLI.

Remember to never do `npm i -D @asyncapi/generator @asyncapi/html-template`

Best practice with dependencies is to always install fixed version and upgrade manually: https://www.asyncapi.com/docs/tools/generator/versioning

**Comment by laat** [comment]
> Best practice with dependencies is to always install fixed version and upgrade manually: https://www.asyncapi.com/docs/tools/generator/versioning

I'm using package-lock.json for lockfile management. Caught this issue in a dependabot PR on my repo.

**Comment by albertodiazdorado** [comment]
It would be super nice if we could have the template work with the new version of the generator :pray:

**Comment by dcorto** [comment]
Hello, any update on this? 

Thanks in advance :+1:

**Comment by derberg** [comment]
fyi https://github.com/asyncapi/cli/pull/1472

any help will be welcome

**Comment by derberg** [comment]
solved with https://github.com/asyncapi/html-template/pull/615
