### ISSUE TITLE
Extract deprecation notice to separate macro

### ISSUE THREAD

**Issue by derberg** [asyncapi/html-template#69]
**Context**

[This](https://github.com/asyncapi/html-template/blob/master/partials/operations/by_tags.html#L34-L50) from `by_tags` and [this](https://github.com/asyncapi/html-template/blob/master/partials/operations/by_tags_no_root.html#L34-L50) from `by_tags_no_root` is exactly the same.

**Description**
1. Next to above mentioned files create a new file, [Nunjucks Macro](https://mozilla.github.io/nunjucks/templating.html#macro)
2. Use this macro in above mentioned files

Example macro -> https://github.com/asyncapi/html-template/blob/master/partials/tags.html
Example macro usage -> https://github.com/asyncapi/html-template/blob/master/partials/message.html#L2 and https://github.com/asyncapi/html-template/blob/master/partials/message.html#L20
Dev instructions -> https://github.com/asyncapi/html-template/tree/master#development﻿

**Comment by derberg** [comment]
video about the issue https://youtu.be/Iqs_2BiNEEo?t=814

**Comment by HashTalmiz** [comment]
Thanks for the video explanation. I'm gonna give this one a try.

**Comment by derberg** [comment]
@HashTalmiz I'm happy that you found the video useful. I'll jump into PR review now

**Comment by derberg** [comment]
fixed with https://github.com/asyncapi/html-template/pull/81
