### ISSUE TITLE
[BUG] ver 3.0.0 unable to determine version of generator

### ISSUE THREAD

**Issue by TertiumOrganum1** [asyncapi/html-template#697]
### ver 3.0.0 unable to determine version of generator

When I try to generate docs I get:
```
Generator Error: This template is not compatible with the current version of the generator (1.17.25). This template is compatible with the following version range: >=2.0.0 <3.0.0.
```
However, I have 2.8.0 generator installed:
```
$ sudo asyncapi --version
@asyncapi/cli/2.8.0 linux-x64 node-v20.13.1
```

### Expected behavior

Should work

### Screenshots

![image](https://github.com/user-attachments/assets/397f0f70-9ec9-4c4e-9026-08b090f3383b)

### How to Reproduce

Using it as always:
```
sudo asyncapi generate fromTemplate asyncapi-cpp-router.yaml @asyncapi/html-template@3.0.0 --param singleFile=true --output ./docs/cpp-router --force-write
```

### 🥦 Browser

None

### 👀 Have you checked for similar open issues?

- [ ] I checked and didn't find similar issue

### 🏢 Have you read the Contributing Guidelines?

- [ ] I have read the [Contributing Guidelines](https://github.com/asyncapi/.github/blob/master/CONTRIBUTING.md)

### Are you willing to work on this issue ?

None

**Comment by TertiumOrganum1** [comment]
Version 0.28.3 works just fine.

**Comment by derberg** [comment]
CLI is not generator. CLI is a mesh of multiple different projects, including generator - so CLI version os not what the console log talks about. Please have a look at https://github.com/asyncapi/html-template?tab=readme-ov-file#usage

**Comment by TertiumOrganum1** [comment]
found out that you should use --use-new-generator flag. Worths mention in docs
