### ISSUE TITLE
Remove unnecessary semicolons from filters

### ISSUE THREAD

**Issue by derberg** [asyncapi/html-template#70]
Remove unnecessary semicolons:
- https://github.com/asyncapi/html-template/blob/master/filters/all.js#L64
- https://github.com/asyncapi/html-template/blob/master/filters/all.js#L105﻿

**Comment by C-Zekeri** [comment]
Hi!
I'd like to work on this issue. Is there anything you'd like me to know beforehand?

**Comment by derberg** [comment]
@C-Zekeri nope, it is a pretty straightforward issue, I just assigned it to you
