### ISSUE TITLE
Figure out how to modify twitter workflow to tweet only about major and minor releases

### ISSUE THREAD

**Issue by derberg** [asyncapi/html-template#71]
**Context**

We agreed with community that we will automatically tweet about all releases from all AsyncAPI packages, but only if it is major or minor release, patches will not be communicated.

[This](https://github.com/asyncapi/html-template/blob/master/.github/workflows/release.yml#L50-L58) workflow so far sends info to Twitter every time there is any release

**Description**

- Figure out how to verify if release is patch and we can skip it
- Consider moving this twitter step to separate workflow that reacts on `release` `created` event and is not part of release pipeline, to not complicate the pipeline to much﻿

**Comment by derberg** [comment]
video about the issue https://youtu.be/Iqs_2BiNEEo?t=878

**Comment by juergenbr** [comment]
Hi, I came across asyncapi via the Hacktoberfest Discord and I'd like to tackle that issue if it's still open.

**Comment by derberg** [comment]
@juergenbr it is still open, please feel free to take it as ask for help whenever it is needed. I assigned the issue to you, I hope you don't mind

**Comment by juergenbr** [comment]
@derberg great, thanks! I have a solution proposal ready, but I'm not 100% sure how to test it with my forked repo.
It's  using a github action to perform the kind of version check that is required based on my understanding.  Is it OK to use external actions or do you prefer a custom implementation to avoid dependency issues?
https://github.com/juergenbr/html-template/blob/feature/tweet-new-release-workflow/.github/workflows/send-tweet-on-release.yml

**Comment by derberg** [comment]
@juergenbr you can normally create releases on a fork and they will have no effect on the upsteam. This is how you can test it.

We do not mind using external actions at all, we just make sure they are released with quality and always look for solution with largest amound of starts. But this is not a written rule.

I don't think [this](https://github.com/juergenbr/html-template/blob/feature/tweet-new-release-workflow/.github/workflows/send-tweet-on-release.yml#L22) will work because step before doesn't have a `check` `id`. Also I don't think your workflow does what we need. We do not have a problem with figuring out if version changed or not, especially if we will switch to a workflow that is triggered by the release. We need a solution that identifies if the released version is `patch` because if it is `patch` we should not tweet to Twitter. Does it make sense?

**Comment by juergenbr** [comment]
@derberg thanks for the quick feedback. Makes sense, yes. [This line](https://github.com/juergenbr/html-template/blob/feature/tweet-new-release-workflow/.github/workflows/send-tweet-on-release.yml#L28) should ensure that the tweet is only sent if the version is either minor or major release, not a patch.
Line 22 to 26 are basically just debug outputs for testing and could be removed.
The version-check action is used to get the type of version change. The action is using semver-diff to get this information,

**Comment by derberg** [comment]
ah so sorry I missed that `steps.check.outputs.type != 'patch'`.
Looks perfect to me. The action that you use is also legit, I even gave it a star.

Just please test if first. You do not have to tweet, 22-26 is enough to test, tweet step can fail. And yeah, open the PR please!

**Comment by juergenbr** [comment]
@derberg I spent some time testing and kept running into an error with the checkversion action. After checking back with the developers it turns out that running the action after the release workflow does not work as intended because the release event does not push any commit that could be checked for a new version.
Since the action can distinguish between the types of version change I suggest keeping the twitter step inside the release workflow because they are connected from a logical point of view but use the line mentioned before to avoid running the step every time.
I did a test run in my fork [here](https://github.com/juergenbr/html-template/runs/1235170116?check_suite_focus=true), could you check and let me know what you think?

**Comment by derberg** [comment]
@juergenbr yeah, it would be just nice to have it separately in another workflow. I was just afraid that release workflow will get more complicated with each additional action. Anyway, I understand what is the blocker here, makes sense. Feel free to do it in the release workflow. Please make sure to add a comment to this action step that it it based on package.json and therefore not valid for other project (like for example our Go projects)
