### ISSUE TITLE
Add parameter to generate pdf from the HTML file

### ISSUE THREAD

**Issue by derberg** [asyncapi/html-template#72]
#### Reason/Context

People still use PDFs to share information, we should support users to easily get PDF out from the HTML. Such functionality is already in [this](https://github.com/derberg/template-for-generator-templates) boilerplate template, so it just needs to be copied.

#### Description

- add `puppeteer` to project dependencies
- add new parameter to template configuration -> https://github.com/derberg/template-for-generator-templates/blob/master/package.json#L62-L65
- creaete new hook responsible for generation, take it from here https://github.com/derberg/template-for-generator-templates/blob/master/hooks/generateExtraFormats.js but just remove pdf and svg generation (these lines https://github.com/derberg/template-for-generator-templates/blob/master/hooks/generateExtraFormats.js#L30-L42)
- update readme

**Comment by derberg** [comment]
video about the issue https://youtu.be/Iqs_2BiNEEo?t=1000

**Comment by HashTalmiz** [comment]
Hey! I'd like to take this up!

**Comment by HashTalmiz** [comment]
In the last step in updating the README, Can I get details as to what I should fill in the other columns, if I add `pdf` as the next entry in `Supported Parameters`?

**Comment by derberg** [comment]
@HashTalmiz it is like in case of the `singleFile` parameter, `pdf` would accept `true` or `false`
