### ISSUE TITLE
Cleanup example spec and development guide

### ISSUE THREAD

**Issue by derberg** [asyncapi/html-template#74]
#### Reason/Context

We should use the same example spec across all templates as much as possible to test them always against the same example. There is such a dummy file in the Generator repo -> https://github.com/asyncapi/generator/blob/master/test/docs/dummy.yml

#### Description
- remove https://github.com/asyncapi/html-template/blob/master/test/spec/asyncapi.yml
- adjust dev guide https://github.com/asyncapi/html-template#development
- adjust script https://github.com/asyncapi/html-template/blob/master/package.json#L26 to use asyncapi file from remote location `ag https://raw.githubusercontent.com/asyncapi/generator/master/test/docs/dummy.yml ./ -o test/output --force-write --watch-template`

**Comment by bszwarc** [comment]
Hi @derberg , I would be happy to help with this one :) Would next week do as well?

**Comment by derberg** [comment]
@bszwarc THAT WOULD BE AWESOME!!! Let me know if you need help 😉 or just ask me on Friday 😄

**Comment by bszwarc** [comment]
Will do!
